default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args:
          - --unsafe
      - id: check-symlinks
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
        args:
          - --maxkb=15000
      - id: detect-private-key
        stages: [pre-commit]

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
        stages: [pre-commit]
      - id: terraform_validate
        stages: [pre-commit]
        exclude: ^examples
        args:
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=always-regenerate-lockfile
      - id: terraform_tflint
        stages: [pre-commit]
        exclude: ^examples
        args:
          - --args=--config=__GIT_WORKING_DIR__/.config/tflint.hcl
          - --env-vars=TFLINT_LOG="info"
      - id: terraform_trivy
        stages: [pre-commit]
      # - id: terrascan
      #   args:
      #     - --args=--non-recursive # avoids scan errors on subdirectories without Terraform config files
      #    # - --args=--policy-type=azure
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--download-external-modules true
      - id: terraform_docs
        stages: [pre-commit]
        args:
          - --args=--config=.config/terraform-docs.yml
        exclude: "^modules|^example|^tools"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
