name: Release
on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/development        
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: list 
      run: ls -la
    - name: replace string in file
      uses: Nambers/ReplaceStringInFile@v1.3        
      with:
        path: ${{ github.workspace }}/a.test
        oldString: REPLACED_BY_GHA
        #oldStringWin: abc123\)\)
        newString: ${{ github.event.repository.name }}
        showFileContent: true
    - name: Replace single file 2
      uses: richardrigutins/replace-in-files@v2
      with:
        files: 'README.md'
        search-text: '{0}'
        replacement-text: ${{ github.event.repository.name }}
    - name: Show contents
      run: cat main.tf
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 20
    # - name: Semantic Release
    #   uses: cycjimmy/semantic-release-action@v4
    #   with:  
    #     extra_plugins: |
    #       conventional-changelog-conventionalcommits@6.1.0
    #       @semantic-release/commit-analyzer
    #       @semantic-release/release-notes-generator
    #       @semantic-release/npm
    #       @semantic-release/git
    #       #conventional-changelog-eslint
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
        #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}