name: Release
on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest        
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:  
        extra_plugins: |
          @semantic-release/changelog@6.0.0
          @semantic-release/git
          @semantic-release/commit-analyzer@8.0.1
          # @semantic-release/release-notes-generator@9.0.3
          # @semantic-release/github@7.2.3
          conventional-changelog-eslint
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}