name: Release
on:
  push:
    branches: [ main ]
    
jobs:
  release:
    runs-on: ubuntu-latest        
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}